# ExternalSecret manifest for claude-hub application secrets
# This syncs secrets from external secret manager into Kubernetes Secrets

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: claude-hub-secrets
  namespace: claude-hub
  labels:
    app.kubernetes.io/name: claude-hub
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: claude-hub
spec:
  # Refresh interval - how often to check for updates
  refreshInterval: 1h

  # Reference to SecretStore
  secretStoreRef:
    name: vault-backend  # Change to aws-secrets-manager or gcpsm-secret-store as needed
    kind: SecretStore

  # Target Kubernetes Secret to create
  target:
    name: claude-hub-secrets
    creationPolicy: Owner  # External Secrets Operator owns this secret
    deletionPolicy: Retain  # Keep secret if ExternalSecret is deleted

  # Data mappings from external secret manager
  data:
  # Example: PostgreSQL credentials
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: claude-hub/postgres  # Path in secret manager
      property: password         # Property within the secret

  # Example: Supabase credentials
  - secretKey: SUPABASE_URL
    remoteRef:
      key: claude-hub/supabase
      property: url

  - secretKey: SUPABASE_SERVICE_KEY
    remoteRef:
      key: claude-hub/supabase
      property: service_key

  # Example: OpenAI API key
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: claude-hub/openai
      property: api_key

  # Example: Anthropic API key
  - secretKey: ANTHROPIC_API_KEY
    remoteRef:
      key: claude-hub/anthropic
      property: api_key

  # Example: Session secret
  - secretKey: SESSION_SECRET
    remoteRef:
      key: claude-hub/app
      property: session_secret

---
# ExternalSecret for monitoring credentials (e.g., Prometheus, Grafana)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monitoring-secrets
  namespace: claude-hub
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: claude-hub
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: monitoring-secrets
    creationPolicy: Owner

  data:
  - secretKey: grafana-admin-password
    remoteRef:
      key: claude-hub/monitoring
      property: grafana_admin_password
